// import { fetchUsers } from "../lib/db.js";

// import Header from "../header";
// import 'bootstrap/dist/css/bootstrap.css'
// import '../globals.css';
// import '../styles/tasklists.css'

// export default function TaskLists() {
//   const Users = async () => {
//     const user = await fetchUsers();

//     return (
//       <html>
//         <head>
//         </head>
//         <body>
//           <Header />
//           <main>
//             <br/>
//             <br/>
//             <div className="row">
//               <div className="col">
//                 <h1>My Task List</h1>
//                 <div class="input-group mb-3">
//                   <div class="input-group-prepend">
//                     <div class="input-group-text">
//                       <input type="checkbox" aria-label="Checkbox for following text input" />
//                     </div>
//                   </div>
//                   <p>peep</p>
//                 </div>
//                 <div class="input-group mb-3">
//                   <div class="input-group-prepend">
//                     <div class="input-group-text">
//                       <input type="checkbox" aria-label="Checkbox for following text input" />
//                     </div>
//                   </div>
//                   <p>peep</p>
//                 </div>
//                 <div class="input-group mb-3">
//                   <div class="input-group-prepend">
//                     <div class="input-group-text">
//                       <input type="checkbox" aria-label="Checkbox for following text input" />
//                     </div>
//                   </div>
//                   <p>peep</p>
//                   <button>Edit</button>
//                 </div>
//               </div>
              
//               <div className="col">
//                 <h1>My Task List</h1>
//               </div>
//               <div className="col">
//                 <h1>My Task List</h1>
//               </div>
//             </div>
//             <div className="row">
//               <div className="col">
//                 <h1>My Task List</h1>
//               </div>
//               <div className="col">
//                 <h1>My Task List</h1>
//               </div>
//               <div className="col">
//                 <h1>My Task List</h1>
//                 {user.map((user, index) => (
//                   <tr key={index}>
//                   <td>{user.User_ID}</td>
//                   <td>{user.User_Fname}</td>
//                   <td>{user.User_Lname}</td>
//                   </tr>
//                 ))}
//               </div>
//             </div>
//           </main>
//         </body>
//       </html>
//     );
//   };
// }
  
import { showData } from "../lib/db.js";
import Header from "../components/header.js";
import 'bootstrap/dist/css/bootstrap.css';
import '../globals.css';
import '../styles/tasklists.css';

export const metadata = {
  title: "Task Lists",
  description: "Generated by create next app",
};

const TaskLists = async () => {
  const account = await showData();

  return (
    <div>
      <Header />
      <main>
        <br/>
        <br/>
        <div className="row">
          <div className="col">
            <h1>My Task List</h1>
            <div className="input-group mb-3">
              <div className="input-group-prepend">
                <div className="input-group-text">
                  <input type="checkbox" aria-label="Checkbox for following text input" />
                </div>
              </div>
              <p>peep</p>
            </div>
            <div className="input-group mb-3">
              <div className="input-group-prepend">
                <div className="input-group-text">
                  <input type="checkbox" aria-label="Checkbox for following text input" />
                </div>
              </div>
              <p>peep</p>
              <button>Edit</button>
            </div>
          </div>

          <div className="col">
            <h1>My Task List</h1>
          </div>
          <div className="col">
            <h1>My Task List</h1>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <h1>My Task List</h1>
          </div>
          <div className="col">
            <h1>My Task List</h1>
          </div>
          <div className="col">
            <h1>My Task List</h1>
            <table>
              <thead>
                <tr>
                  <th>User ID</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                </tr>
              </thead>
              <tbody>
                {account.map((account, index) => (
                  <tr key={index}>
                    <td>{account.Account_ID}</td>
                    <td>{account.Account_Username}</td>
                    <td>{account.Account_Email}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
};

export default TaskLists;
